### ISSUE TITLE
Option for content slug instead of ID

### ISSUE THREAD

**Issue by dipankarmaikap** [wpengine/atlas-content-modeler#192]
### Is your feature request related to a problem? Please describe.
Currently If I create a Model and then add content it generated its slug based on DatabaseID. IT should offer an option slug like the default WP post and page do.

### Describe the solution you'd like
A simple option like its provided in default WP post type based on the title. It has to be unique and auto generated also have a option for editing.

### Describe alternatives you've considered
Currently I add an extra text field for the slug and this is not optimal + there is always a chance of having same slug.
### Additional context
Currently We have an option to set a created field as Title Field and we can use this to generate the auto slug and then if the user choose to overwrite they can do that.

![image](https://user-images.githubusercontent.com/45673791/124800962-e455e680-df73-11eb-9f9b-0ae72c456f11.png)

**Comment by nickcernis** [comment]
Thank you for the feature suggestion, Dipankar!

I added this to our product backlog so our team can discuss how best to support custom slugs. [Team reference: BH-1116.]

As a workaround for now, you can enable custom slugs on all Content Modeler post types like this:

1. Create a file in your WordPress installation at `wp-content/plugins/content-modeler-customizations.php` with this content:

```php
<?php
/**
 * Plugin Name: Atlas Content Modeler Customizations
 * Plugin URI: https://github.com/wpengine/atlas-content-modeler/issues/192
 * Description: Model content for headless WordPress.
 * Version: 0.1.0
 * Requires at least: 5.2
 * Requires PHP: 7.2
 * License: GPLv2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 *
 * @package AtlasContentModelerCustomizations
 */

namespace WPE\AtlasContentModelerCustomizations;

add_filter( 'screen_options_show_screen', __NAMESPACE__ . '\show_screen_options', 11, 2 );

/**
 * Shows the “Screen Options” drop-down on post types registered by Atlas Content Modeler.
 *
 * @param bool       $show_screen The current state of the screen options dropdown.
 * @param \WP_Screen $screen Information about the current screen.
 *
 * @return bool The new state of the screen options dropdown. (True to enable.)
 */
function show_screen_options( bool $show_screen, $screen ): bool {
	$models = get_option( 'atlas_content_modeler_post_types' );
	if ( in_array( $screen->post_type, array_keys( $models ), true ) ) {
		return true;
	}

	return $show_screen;
}

```

2. Activate the “Atlas Content Modeler Customizations” plugin at Plugins → Installed Plugins.

3. When you edit an entry, click “Screen Options” in the top-right and activate “Slug” in the Screen Elements panel, as pictured below.

This will give you an editable slug field that automatically resolves any conflicts when the entry is saved. (WordPress will append `-2` to the slug if a custom slug already exists for that entry type, just like it does with posts and pages.)

<img width="1287" alt="Screenshot 2021-07-08 at 10 29 07" src="https://user-images.githubusercontent.com/647669/124889715-a4c0e600-dfd7-11eb-8a5e-1690b87f8464.png">

**Comment by blakewilson** [comment]
This would be a really handy feature to have in ACM!

For users who may be using ACM/Faust, customizing the slug becomes very important when wanting individual single pages for posts.

For example, say you have a content model for `Team Members` and you want to display a list of them in addition to having a page for each team member. The only unique identifier you could use would be the database ID or ID, which would not be great for a unique URL:

```
https://my-site.com/team/cG9zdDo0Mg==
```

Currently, a user would have to either:
* Use the database ID (not recognizable, bad SEO)
* Create a custom field for a slug. This comes with a disadvantage (especially in Faust) as the query becomes more complex

**Comment by mindctrl** [comment]
@dipankarmaikap as of version 0.10.0, which was released today, it's possible to define the slug by turning it on in the Screen Options tab as shown in the screenshot above. It's no longer necessary to add the custom code to your site. In the future we'll work on deriving it from the post title like WP does.
