### ISSUE TITLE
Warning showing in login page : array_key_exists(): The first argument should be either a string or an integer.

### ISSUE THREAD

**Issue by dipankarmaikap** [wpengine/atlas-content-modeler#193]
A clear and concise description of the bug goes here.
Everything works fine but when i logout and try to login it shows a big php warning below the login form.

`
Warning: array_key_exists(): The first argument should be either a string or an integer in C:\laragon\www\headlesswp\wp-content\plugins\atlas-content-modeler\includes\publisher\class-publisher-form-editing-experience.php on line 426
`

### To reproduce
1. Create a content model 
2. Add few items to it 
3. Change the Title Field to a different field 
4. Logout and try log back and See the error

### Expected behavior
So far everything is working as expected and everything is showing in the graphql as expected but the warning errors are present in the login screen and it should not have.

### Screenshots
![image](https://user-images.githubusercontent.com/45673791/124899279-95549380-dffd-11eb-96ec-56f7ac5d2ab3.png)

### Version information
- Plugin version: 0.4.1
- WordPress version: 5.7.2
- Operating system: Windows
- Browser: Chrome Version 91.0.4472.124 (Official Build) (64-bit)

### Additional context
I have checked the following line in the plugin file as mentioned in the warning and found that the warning is coming because the `array_key_exists( $post_type, $this->models)` is receiving boolean value. Here `$post_type` is returning ` boolean false` when I do `var_dump`.

![image](https://user-images.githubusercontent.com/45673791/124900903-20825900-dfff-11eb-9f51-db4f565cbfa1.png)

**Comment by nickcernis** [comment]
Thank you for the report, Dipankar!

I can reproduce this and have opened a suggested fix in https://github.com/wpengine/atlas-content-modeler/pull/194.

**Comment by nickcernis** [comment]
The fixed was merged to main but is not in production yet. Reopening open until this is in production.

**Comment by nickcernis** [comment]
0.4.2 is out now with a fix for this issue. Thank you again for the report!
