### ISSUE TITLE
Customizable Menu Icons

### ISSUE THREAD

**Issue by NicktheGeek** [wpengine/atlas-content-modeler#195]
### Is your feature request related to a problem? Please describe.
Clients using a CMS often use icons to help quickly find menu items in the dashboard. If I create a "staff" model for them to create office staff entries that I will display on the front end, they need to be able to tell the difference between this model and other models at a glance.

### Describe the solution you'd like
Ideally there would be an upload field to select an icon or at least a field to set a dashicon.

### Describe alternatives you've considered
So far I've not delved into this too far. I assume there is likely a filter that will make it possible to do this in WordPress, but it shouldn't require that.

**Comment by nickcernis** [comment]
Thanks for the feedback, Nick! This feature was merged to main as part of https://github.com/wpengine/atlas-content-modeler/pull/176 and will be part of the next release.
