### ISSUE TITLE
Customizable Menu Position

### ISSUE THREAD

**Issue by NicktheGeek** [wpengine/atlas-content-modeler#196]
### Is your feature request related to a problem? Please describe.
Similar to https://github.com/wpengine/atlas-content-modeler/issues/195. The order elements appear in the menu mater. It would be helpful to be able to control where the model shows in the menu.

### Describe the solution you'd like
Ideally there would be a field, maybe a number select, to control where in the menu models appear.

### Describe alternatives you've considered
Again, there is likely a WordPress filter that could control this, but at that point I might as well register the CPT and fields manually too.

**Comment by nickcernis** [comment]
Tracked at https://wpengine.atlassian.net/browse/MTKA-1362.

**Comment by mindctrl** [comment]
Since ACM has entered an end-of-life phase and won't be receiving any new features like this, I'm going to close this issue. Source: https://github.com/wpengine/atlas-content-modeler/blob/main/docs/end-of-life/index.md
