### ISSUE TITLE
API Identifier label doesn't match behavior

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/atlas-content-modeler#227]
When creating a new Content Model, the label for "API Identifier" states: 

> Auto-generated from the plural name and used for API requests.

But the behavior is that the value of the field is being generated from the "Singular Name" field

### To reproduce
1. Go to the "Create New Model" page
2. Fill in a value in the "Singular Name" field
3. Watch the "API Identifier" field get auto populated
4. Fill in a value in the "Plural Name" field
5. Nothing changes in the "API Identifier" field, as the field description describes it should

### Expected behavior
I would expect that the "API Identifier" field would either say that it's auto-generated from the "Singular Name" field

or

I would expect that the auto-generated value come from the "Plural Name" field as described.

### Screenshots

![acm-api-field-bug](https://user-images.githubusercontent.com/1260765/129763790-6647fd78-42e7-47e9-9622-a2cb76893cc3.gif)

### Version information
- Plugin version: 0.5.0
- WordPress version: 5.8

**Comment by mindctrl** [comment]
@jasonbahl looks like an old UI there. Try again on latest `main`.

It should look like this now:
![image](https://user-images.githubusercontent.com/1254870/129776852-b965ee1b-3b7c-4e60-8b77-49c2ce0dcb3c.png)

**Comment by mindctrl** [comment]
Was fixed here https://github.com/wpengine/atlas-content-modeler/commit/be897ae34b5e0b8ca7b299d2342a2196cc8d9d9a

**Comment by jasonbahl** [comment]
@mindctrl ah yes. 🤦🏻 

After rebuilding with `rm -rf ./parcel-cache` and `npm run build` this is not an issue. 

Thanks!
