### ISSUE TITLE
Add filter support for ACM models

### ISSUE THREAD

**Issue by dipankarmaikap** [wpengine/atlas-content-modeler#229]
### Is your feature request related to a problem? Please describe.
Currently there is really no option available for filter for the models created. 
1. ACM now supports taxonomies which is a great feature but there is no way to filter by taxonomies.
2. As ACM does not offer option for slug yet cant filter by this either. (Technically its possible but its not user friendly)
3. Does not support filter by author.

### Describe the solution you'd like
In wp graphql its offers all the above mentions option for all the native post types, Something similar.

### Describe alternatives you've considered
There is really no real alternative for this one thing would be to fetch all the data and then filter in the front-end.

**Comment by mindctrl** [comment]
Thanks @dipankarmaikap! We'll look into this.

Internal note: we're tracking this in Jira under BH-1190.

**Comment by mindctrl** [comment]
@dipankarmaikap just noting that it's possible to query by author now. Taxonomy filtering is coming in the near future. We'll update you here when that's available.

**Comment by nickcernis** [comment]
Work in progress on documenting taxonomy queries/filtering: https://github.com/wpengine/headless-docs/pull/104

Internal link for our reference: https://wpengine.atlassian.net/browse/MTKA-1310

**Comment by nickcernis** [comment]
ACM now supports filtering by taxonomy, slug and author as requested.

**Upgrade to the latest version of ACM**, then you can:

## Fetch posts by taxonomy

1. Install the [WPGraphQL Tax Query plugin](https://github.com/wp-graphql/wp-graphql-tax-query).
2. See our [taxonomy query guide](https://github.com/wpengine/headless-docs/blob/devrel/dev/atlas-content-modeler/tutorial/models/taxonomies/query.mdx) for example queries.

## Fetch a post by slug

1. Enable slugs for your post type in the Screen Options when editing any post:

<img width="1143" alt="Screenshot showing the “slug” checkbox ticked in the Screen Options area." src="https://user-images.githubusercontent.com/647669/149345661-89302d6f-4184-450f-87e3-cc06c56939f9.png">

2. Enter a slug for your entry in the sidebar, such as "custom".

3. Use this query to fetch a post by its slug (for a model named "rabbit"):

```
{
  rabbitBy(slug: "custom") {
    title
  }
}
```


## Fetch posts by author

1. Change the author from the post sidebar if needed.

2. Use this query to fetch entries by author (for a model named 'rabbits'):

```
{
  rabbits(where: {authorName: "local"}) {
    edges {
      node {
        title
      }
    }
  }
}
```
