### ISSUE TITLE
Show Taxonomies connected to Content Models

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/atlas-content-modeler#233]
### Is your feature request related to a problem? Please describe.

From the "Content Models" screen, I cannot easily see which models are associated with which taxonomies. 

![Screen Shot 2021-08-17 at 12 46 09 PM](https://user-images.githubusercontent.com/1260765/129783858-87d738e5-a27d-4624-b195-5d1566a4ccd0.png)

From the "Taxonmies" screen, I _can_ easily see which Taxonomies are associated with which Models. 

![Screen Shot 2021-08-17 at 12 44 50 PM](https://user-images.githubusercontent.com/1260765/129783885-edc25f47-d26b-4e0d-b554-6006004823c7.png)

### Describe the solution you'd like
I would like to see which Taxonomies are associated with a Content Model from the Content Model screen. 

![Screen Shot 2021-08-17 at 12 52 27 PM](https://user-images.githubusercontent.com/1260765/129783995-35908227-0672-4856-9f06-44c1ac577fab.png)

**Comment by nickcernis** [comment]
Tracked at https://wpengine.atlassian.net/browse/MTKA-1361.
