### ISSUE TITLE
Field or option to support an array of media items

### ISSUE THREAD

**Issue by natac13** [wpengine/atlas-content-modeler#234]
### Is your feature request related to a problem? Please describe.
Nope

### Describe the solution you'd like
Just curious if there could be a field option to support an array of media items

### Describe alternatives you've considered
Writing custom code to register the CPT and custom fields

**Comment by mindctrl** [comment]
@natac13 thanks for the request! We've been discussing this idea and agree we need something like this. We'll let you know when we have more to share.

**Comment by nickcernis** [comment]
Tracked at https://wpengine.atlassian.net/browse/MTKA-1305.

**Comment by mindctrl** [comment]
Added in 0.15.0
