### ISSUE TITLE
Extend existing Post Types / Taxonomies

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/atlas-content-modeler#237]
### Is your feature request related to a problem? Please describe.

I would like to use ACM to create Content Models and Taxonomies, but would also like to use it to customize and extend Post Types and Taxonomies that are not created by ACM. 

For example, if using a 3rd party plugin, such as WooCommerce, and I needed to add some custom fields to the Product and Order Post Types, I would like to be able to "Extend" existing content models (post types) and add fields using the ACM field builder. 

### Describe the solution you'd like

My oversimplification might be something like the following: 

I could see Custom Content Models created by ACM, but also see existing Content Models that were registered by other plugins or theme code. For example, the "Product" Custom Post Type would show under "Existing Content Models"

![Screen Shot 2021-08-18 at 10 09 20 AM](https://user-images.githubusercontent.com/1260765/129933212-4d1c8c8a-fc3b-411e-b1af-1653791d4086.png)

I could then click into the Product model to extend it, and add fields, in the same way I would add fields to a Model created by ACM:

![Screen Shot 2021-08-18 at 10 04 24 AM](https://user-images.githubusercontent.com/1260765/129932466-7bbbafdf-7e9c-4652-811a-ac1793143379.png)

### Describe alternatives you've considered
Right now, I can add custom fields to existing / 3rd party post types and taxonomies using Advanced Custom Fields or Metabox.io, but would like to do this using ACM.

**Comment by nickcernis** [comment]
@jasonkonen Do we want to spin up a Jira ticket/epic to track this one?

**Comment by alinademi** [comment]
+1 for this
