### ISSUE TITLE
Export content models for deployment

### ISSUE THREAD

**Issue by jmotes** [wpengine/atlas-content-modeler#239]
### Is your feature request related to a problem? Please describe.

I'm in the process of architecting a headless solution for a page builder platform where we will deploy the same plugins/theme for each WP instance and allow each site manager to place blocks on pages and enable features to customize their site to their liking. I've been overwhelmed by the amount of plugins necessary to cobble together to create a headless architecture with WP that works for us.

### Describe the solution you'd like

If Atlas Content Modeler had a capability to export a JSON or PHP file for the resulting content model, we could bundle that in a plugin to enable instantly creating the content models for each website on the platform.

### Describe alternatives you've considered

ACF + WPGraphQL  + WPGraphQL for Advanced Custom Fields

**Comment by mindctrl** [comment]
@jmotes thanks for the request! We've started planning an export/import feature. I don't have an ETA yet on when we'll get it shipped, but we'll update you here when we have more info.

**Comment by nickcernis** [comment]
Import/Export is now available under the Content Modeler → Tools menu.

We have plans to extend this with a WP-CLI command to support automated import in the future.
