### ISSUE TITLE
WPGraphQL mutation support

### ISSUE THREAD

**Issue by natac13** [wpengine/atlas-content-modeler#240]
### Is your feature request related to a problem? Please describe.
Nope

### Describe the solution you'd like
Would be really nice to have the custom fields which are created on each model to appear on the respective create and update mutations which Wpgraphql adds for each post type.

**Comment by nickcernis** [comment]
Thanks for the request, @natac13! We also see the appeal of mutations. I'll leave this open so we can let you know if we add them.

**Comment by natac13** [comment]
If a PR was done for this would the team be open to adding it? The reason I ask is because as it stands, if I were to use this plugin, I would have to figure out what the meta fields are being named so that I can make custom code for`mutateAndResolve` handlers. And since I am authoring that code, the code to register the CPT and field I might as well do myself too. 

I am really not trying to be rude or demanding, as I know this is completely open source project. I am just confused and wondering why the fields being added to the create and update mutations from wpgraphql is an 'if' feature.

Thanks for the quick response!

**Comment by nickcernis** [comment]
Thanks for offering to implement mutations, Sean.

We started with reading data as that's the more common use case, but we recognise that mutation is an essential feature for many. (It's likely we'll add them at some point — I just didn't want to make any promises before we know when.)

We're planning a round of refactors in upcoming releases leading to 1.0. It may be worth waiting until then before contributing larger features like mutations. Thanks again for voicing your support for the feature and for getting involved with the project this early on.

**Comment by natac13** [comment]
Sounds terrific!

**Comment by nickcernis** [comment]
Tracking internally at https://wpengine.atlassian.net/browse/MTKA-1359.

**Comment by eligundry** [comment]
Follow up question on this: Would this also allow us to programmatically manipulate data in ACM using the Wordpress REST API? Would love to be able to mass import data into ACM using either mutations or the API.

**Comment by nickcernis** [comment]
Mutations are now available in ACM 0.17! 🎉

Docs are available here:

https://github.com/wpengine/atlas-content-modeler/blob/main/docs/mutations/index.md
