### ISSUE TITLE
Select Field Support

### ISSUE THREAD

**Issue by natac13** [wpengine/atlas-content-modeler#241]
### Is your feature request related to a problem? Please describe.
nope

### Describe the solution you'd like
A select type field. Similar to a radio button, checkbox or select input.

**Comment by nickcernis** [comment]
This is on the way!

We have some final polish to do in https://github.com/wpengine/atlas-content-modeler/pull/210 (that we put on hold for a short time to focus on other work), but the Multiple Choice field will be available when that's complete. It will support checkbox lists and radio buttons to begin with.

![128188775-4ed7cd23-41ed-4cf7-9917-6e53fc38b538](https://user-images.githubusercontent.com/647669/130033699-024168aa-9110-496e-9c9f-ff3a916865e9.png)

**Comment by natac13** [comment]
That looks amazing!! Great to hear

**Comment by nickcernis** [comment]
The Multiple Choice field is now live! Please feel free to check it out in the latest version.
