### ISSUE TITLE
Bi-directional fields

### ISSUE THREAD

**Issue by jmotes** [wpengine/atlas-content-modeler#242]
### Describe the solution you'd like
Ability to create M:N relationships between content models and see the resulting selections on each related item (not just the item the link was created on).

I saw the PRs for 1:1 and 1:M so figured this was planned but would be nice to know for sure if we can expect to use Atlas Content Modeler in the future for our needs.
 
### Describe alternatives you've considered
https://www.acf-extended.com/features/field-settings/bidirectional-fields

**Comment by nickcernis** [comment]
Thank you for the feature request, @jmotes.

As you noticed from the [PR](https://github.com/wpengine/atlas-content-modeler/pull/225), we're currently implementing one-way relationships. We've talked about extending this to bi-directional fields later, but I can't yet make any promises about if or when that would happen. I appreciate you requesting it, though, as it helps us to gauge demand.

I'll leave this open so we can share updates as we know more.

**Comment by mindctrl** [comment]
@jmotes version 0.10.0 was released today, and it includes the ability to define/manage bidirectional relationships from both sides of the connection. https://github.com/wpengine/atlas-content-modeler/blob/041abcfcb24e082069aae812c4c9d631952060e1/readme.txt#L56-L59

**Comment by jmotes** [comment]
@mindctrl oh wow, thank you so much!
