### ISSUE TITLE
feature: flex/repeater field

### ISSUE THREAD

**Issue by Marco-Daniel** [wpengine/atlas-content-modeler#269]
### Describe the solution you'd like

A flexible / repeater field like ACF pro has.

The only anoying thing with ACF is that you define the layouts/blocks inside the flex field. It would be awesome if you could define layouts/blocks seperate from the flex/repeater field for better reuse.

**Comment by nickcernis** [comment]
Thanks for your request, @Marco-Daniel!

We're about to ship a new “Relationship” field that may satisfy the use case of having a reusable group of fields.

You can see a sneak-peek of the field (from the developer side) in the screenshots from [this PR](https://github.com/wpengine/atlas-content-modeler/pull/203).

It will allow you to:
1. Define a model containing one or more fields.
2. Create a relationship field in other models that allow you to add one or more entries from the first model.
3. Give the publisher a modal to choose other entries (and eventually add new ones).

This could satisfy a lot of use cases for repeaters while encouraging reusability.

I'll leave this issue open until the feature is shipped so you can have a chance to play with it and see if it does what you need.

**Comment by ahollister** [comment]
I can second the need for something like this. 

I have a use case:

- Need to build a cooking timer for different cuts of beef.
- Each cut has a variety of 'thickness' objects, each of which have an array of cooking methods + associated time to cook.

You would think the thing to do here would be create a post type for the meat cuts, and maybe another content type or some taxonomies to attach different data points to each.

However the cooking times in the 'thicknesses' can vary based on the cut it's attached to, which means a relationship field can only satisfy that use case with a very convoluted setup and might not even be possible. 

This is where I'd normally make a decision to go in a different direction and keep everything within the individual meat cuts as nested groups/repeater fields of some kind. It's this kind of case where repeaters + groups and the ability to nest them would be a huge enhancement and would allow me to achieve pretty much whatever data structure I'm going to need with Atlas Content Modeler.

**Comment by nickcernis** [comment]
Tracking internally at https://wpengine.atlassian.net/browse/MTKA-1357.

**Comment by mindctrl** [comment]
Since ACM has entered an end-of-life phase and won't be receiving any new features like this, I'm going to close this issue. Source: https://github.com/wpengine/atlas-content-modeler/blob/main/docs/end-of-life/index.md
