### ISSUE TITLE
field used as entry title, doesn't support `NodeWithTitle` interface in GraphQL

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/atlas-content-modeler#281]
A clear and concise description of the bug goes here.

### To reproduce
1. Create a model using ACM
2. Create a text field named `title`
3. Select "Use this field as the entry title"
4. Create a post of that model's post_type
5. Enter a value as the title
6. Publish the entity
6. Create a page of the page post_type and publish it with a title
6. Query with GraphQL using `NodeWithTitle` fragment (as seen below)
7. See that Model doesn't output a title, but the Page does

### Expected behavior
I expect to be able to use GraphQL to query the value of the `title` when I set a field to "use as the entry title"

### Screenshots
**Create a Model**

![Screen Shot 2021-09-21 at 4 00 25 PM](https://user-images.githubusercontent.com/1260765/134253607-615753af-4e95-4443-beb1-5312c291dd55.png)

**Field set to "use as entry title"**

![Screen Shot 2021-09-21 at 4 01 26 PM](https://user-images.githubusercontent.com/1260765/134253682-292d9948-a310-42cb-bf89-bf40ad0a9ea5.png)

**Post Edit Screen**

✅  Editing the "book" model allows me to save the book with "test" as the value of the "title" field

![Screen Shot 2021-09-21 at 3 54 04 PM](https://user-images.githubusercontent.com/1260765/134252984-4b0aa6fb-7f0f-4685-b5d1-1baa231bc34c.png)

**Post List Screen**

✅  The post_list screen shows the title "test" as expected

![Screen Shot 2021-09-21 at 3 53 22 PM](https://user-images.githubusercontent.com/1260765/134252893-1df8139f-2a7f-4cba-b929-4ad5e65b2147.png)

**Query in GraphQL**

Using the following query: 

```graphql
{
  contentNodes {
    nodes {
      __typename
      ... on NodeWithTitle {
        title
      }
    }
  }
}
```

We can execute the query and see that other post types output the `title`, much like we see in the WP Admin table list for each post_type, but the "Book" entries don't have a title.

![Screen Shot 2021-09-21 at 4 08 12 PM](https://user-images.githubusercontent.com/1260765/134254294-f52818f7-dcd9-4bc3-95dc-7cef87dde607.png)

I believe this will impact tools such as Gatsby and the FaustJS framework, as users will expect to be able to query the title and get a value matching what they see in the admin.

### Version information
- Plugin version: 0.5.0
- WordPress version: 5.8.1

**Comment by nickcernis** [comment]
Fixed in https://github.com/wpengine/atlas-content-modeler/pull/362, planned for the upcoming 0.11 release.
