### ISSUE TITLE
Sidebar menu item not updated automatically when plural name is changed

### ISSUE THREAD

**Issue by mindctrl** [wpengine/atlas-content-modeler#349]
When changing the plural name of a model, the sidebar menu item is not updated automatically. It requires a page refresh. This is inconsistent with the add/delete behavior.

### To reproduce
1. Create a new model
2. See new sidebar menu item
3. Edit model
4. Change plural name
5. See sidebar menu item remain the same

### Expected behavior
The sidebar menu item to be updated automatically

### Screenshots
Optionally add screenshots to help explain your problem.

### Version information
- Plugin version: `main` branch
- WordPress version: latest
- Browser: Safari

### Additional context

https://user-images.githubusercontent.com/1254870/141134843-65874be8-2239-436b-ac47-671ce2de2cd4.mov

**Comment by nickcernis** [comment]
Fixed in https://github.com/wpengine/atlas-content-modeler/pull/360.
