### ISSUE TITLE
Inconsistent label used for taxonomy slug/ID

### ISSUE THREAD

**Issue by mindctrl** [wpengine/atlas-content-modeler#350]
The taxonomies page under Content Modeler > Taxonomies uses inconsistent labeling when referring to the taxonomy slug. The add/edit form calls it "Taxonomy ID" and the list table calls it "Slug".

### Expected behavior
Consistent terminology

### Screenshots
![image](https://user-images.githubusercontent.com/1254870/141164914-912213c7-2641-47b9-bb0b-d378be2bf9dd.png)

**Comment by nickcernis** [comment]
Fixed in https://github.com/wpengine/atlas-content-modeler/pull/359.
