### ISSUE TITLE
Publishing content in a new Model leads to 404s

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/atlas-content-modeler#386]
A clear and concise description of the bug goes here.

### To reproduce
1. Create a new public model using ACM
2. Create a new entry in that Model
3. Visit the post of that model
4. See 404

### Expected behavior
I expect to be able to create a model in ACM, then publish content of that model and have it publicly visible. 

Currently, I have to go to manually flush permalinks after creating a model. 

### Possible solution
When creating / updating / deleting ACM models, permalinks should automatically be flushed by ACM.

### Screenshots
I recorded a video walking through some things I was experiencing with ACM and this issue is covered in the video.
https://www.youtube.com/watch?v=SmmGqy7bXxo

### Version information
- Plugin version: 0.11.0
- WordPress version: 5.8.2
- Operating system: Mac OSX 11.6.1
- Browser: Chrome v96.0.4664.93

**Comment by mindctrl** [comment]
Nice catch. Thanks for reporting this.

**Comment by nickcernis** [comment]
Also logged at https://wpengine.atlassian.net/browse/MTKA-1364.

**Comment by nickcernis** [comment]
Fixed by https://github.com/wpengine/atlas-content-modeler/pull/390 (unreleased, but scheduled for 0.13.0). Thanks again for the report!
