### ISSUE TITLE
Fields set to "use this field as entry title" aren't fully respecting the title responsibilites

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/atlas-content-modeler#388]
This is kind of 2 issues, but both related to creating a field and setting it as "use this field as entry title"

## 1: Slugs aren't generated

When creating a field on a model and marking it as "use this field as the entry title" the behavior doesn't match what the core WordPress title does. Namely, the slug isn't being generated from this field, and as mentioned in #280, the value isn't stored in the `post_title` column in the database.

## 2: Can't name the field "title"

Also, I'm unable to name a field `title` even if I set it to use as the entry title. The client validation prevents this. 

I believe that if I have a field marked as "use this field as the entry title", the validation for using the name "title" should be lifted, and the field should behave as the title. 

### To reproduce
1. Create a new ACM model
2. Add a new text field
3. Name the field "title" and see the validation error that the name can't be used
4. Mark the field "use the field as the entry title" and see the validation error still present. 
5. Try to save the field anyway, and you cannot save it while named `title`, even though you've opted to have the field be the `title`

### Expected behavior
I would expect that if I mark a field "use this field as the entry title" that it would behave like the core title field. It would let me reference it by the name `title`, it would work with existing core methods and filters such as `get_the_title()`, etc. I would expect the title to be used to generate the slug, and I would expect the title to be stored in the `post_title` column and included in search. 

### Screenshots
I recorded a video walking through some things I was experiencing with ACM and this issue is covered in the video.
https://www.youtube.com/watch?v=SmmGqy7bXxo

### Version information
- Plugin version: 0.12.0
- WordPress version: 5.8.2
- Operating system: Mac OSX 11.6.1
- Browser: Chrome v96.0.4664.93

**Comment by mindctrl** [comment]
Yeah, we need to spend some time polishing the title experience. I'll share some thoughts later.

**Comment by mindctrl** [comment]
Slugs were addressed in #507. Using field names that would conflict with names WPGraphQL automatically registers is something we're addressing in a separate issue.
