### ISSUE TITLE
Editor not loading

### ISSUE THREAD

**Issue by bz-kmnn** [wpengine/atlas-content-modeler#399]
### What is happening 
When entering the editor section for a post type created with acm the editor sometimes won't load correctly, instead showing blank page where the editor is supposed to be.

Console shows error: TypeError: A.oldEditor.getDefaultSettings is not a function.
Reference js file: atlas-content-modeler/includes/publisher/dist/index.js?ver=0.12.1:1

### Version information
- Plugin version :0.12.1
- WordPress version: 5.8.3

### Possible fix
Add priority 20, 1 to function "enqueue_assets" in includes\publisher\class-publisher-form-editing-experience.php line 73 
Fix makes the function call come later in stack so other dependencies are in place.

**Comment by nickcernis** [comment]
Thanks for the helpful report and suggested fix, @bz-kmnn!

I was able to reproduce this consistently by adding a Rich Text field and then throttling network speed in Chrome to "Slow 3G".

<img width="440" alt="Screenshot 2022-01-13 at 15 32 28" src="https://user-images.githubusercontent.com/647669/149349523-e055c6e4-0bf0-4df7-8465-77919a4735f6.png">

We'll look into it some more and fix it in an update.
