### ISSUE TITLE
Fatal error in post title filtering if 2nd argument is missing

### ISSUE THREAD

**Issue by luketimothyjones** [wpengine/atlas-content-modeler#441]
Function in question:
https://github.com/wpengine/atlas-content-modeler/blob/12717a6cebbbb6cebbb1374fabdde0170ab4cc29/includes/publisher/class-publisher-form-editing-experience.php#L618-L645

Potential patch:
```PHP
public function filter_post_titles( string $title, int $id = -1 ) { 
    if ( $id === -1 ) {
        return $title;
    }

    $post_type = get_post_type( $id );
    ...
```

### To reproduce
1. Call `wp_insert_post_data` such that `filter_post_titles` will be called with an array as the second argument
    a. I'm not certain this is the exactly scenario, it could also be that it's getting called without a second argument altogether.
2. See error

### Expected behavior
Title passes through unscathed

### Screenshots
![Error](https://user-images.githubusercontent.com/6316047/154376871-9dd98133-eaac-4901-bdb1-b2bd8ca51690.png)

### Version information
- Plugin version: 0.14.0
- WordPress version: 5.9 on PHP 8.0
- Operating system: Windows 10 x64
- Browser: Firefox 97.0

### Additional context
I encountered this while working with BuddyBoss, an extension of BuddyPress.

**Comment by mindctrl** [comment]
This should be addressed by #446  since this method is being removed there. Closing this. Will re-open if necessary. Thanks for the report!
