### ISSUE TITLE
"Changed Linked X" list not paginated when editing relationships of a Model

### ISSUE THREAD

**Issue by desmondhoward** [wpengine/atlas-content-modeler#443]
The list to edit the linked relationships of a Model only shows the last page and doesn't allow scrolling to the other pages.

### To reproduce
1. Create 2 models where model A has a one-to-many relationship to model B 
2. Create more than 5 model B entities
3. Create a model A entity and click "Change Linked Model Bs"
4. Error: Notice that its not possible to see all Model B entities

### Expected behavior
Scrolling is allowed to see all of the Model B entities, not just the last 5.

### Screenshots
<img width="552" alt="Screen Shot 2022-02-22 at 6 03 19 PM" src="https://user-images.githubusercontent.com/96273496/155234318-b8677e67-bc26-4e06-b473-4eb655467e13.png">

### Version information
- Plugin version: 0.14.0
- Operating system: macOS
- Browser: Chrome

**Comment by nickcernis** [comment]
Thanks for the report @desmondhoward. I wasn't able to reproduce this so far — I see paginated entries for if there are more than 5 “model B” posts:

https://user-images.githubusercontent.com/647669/155300207-e6a5ac35-9695-40d3-91fa-7e879935e4d9.mov

First, **it's worth double checking that all your posts are published** — ACM does not show draft or in-review posts in the relationship modal.

Next, for pagination to work, **ACM needs REST responses to include the `X-WP-Total` header** to learn how many Model B posts WordPress has in total. WordPress sends this header by default but other plugins can filter and remove headers.

If you're comfortable using the terminal you can try running `curl -I "http://example.com/wp-json/wp/v2/posts?per_page=5&page=1"` in a terminal (replacing `http://example.com` with your WordPress URL) and checking that you see `X-WP-Total: [post count]` in the response.

If you _don't_ see `X-WP-Total` in the response, try temporarily disabling other plugins until you do, or contacting your host if this is not a local WordPress site to let them know the header is being removed.

If you _do_ see `X-WP-Total` in the response, please can you share the full response of the curl command here? Or, if you prefer not to run these commands and your WordPress site is public, feel free to share the URL for us to investigate.

**Comment by desmondhoward** [comment]
thanks for the quick response. 
it looks like the "WPGraphQL JWT Authentication" plugin was the source of the problem, as it was removing the `X-WP-Total` and `X-WP-TotalPages` headers from the response. disabling it allows the pagination to work properly.

thanks again + great work on the plugin!

**Comment by nickcernis** [comment]
Glad you were able to resolve it, @desmondhoward, and thanks for the kind words!

There's a PR to fix headers being stripped by the WPGraphQL JWT plugin:

https://github.com/wp-graphql/wp-graphql-jwt-authentication/pull/118/

If you need a workaround to use the plugin alongside ACM now you could apply the suggested fix manually:

https://github.com/wp-graphql/wp-graphql-jwt-authentication/pull/118/files

**Comment by desmondhoward** [comment]
@nickcernis I noticed that PR too, but based on the activity (last touched Nov 2020) I'm not expecting it to merge anytime soon.
even further, based on the unanswered issues I imagine we'll seek other alternatives in achieving our auth. always open to suggestions 😄

**Comment by nickcernis** [comment]
@desmondhoward As long as you're using HTTPS and don't need JWT for some reason, basic auth works with WPGraphQL: https://github.com/WP-API/Basic-Auth
