### ISSUE TITLE
Cannot directly change case of model name on edit

### ISSUE THREAD

**Issue by ericosullivanwp** [wpengine/atlas-content-modeler#535]
If I create a model of `car`, I cannot change the name to `Car` while editing the model as validation kicks in saying that a model with that name already exists. It can be worked around via a temp name, e.g., `car` -> `Car1` -> `Car`.

### To reproduce
1. Create model called `car`
2. Click on '....' to edit
3. Change the name to `Car` and save
4. Validation message appears that a model with that name already exists

### Expected behavior
Expectation is that I can change `car` to `Car` directly

### Version information
- Plugin version: 0.17.0
- WordPress version: 5.9.3
- Operating system: macos
- Browser: Firefox 100.0b3

**Comment by nickcernis** [comment]
Tracking at https://wpengine.atlassian.net/browse/MTKA-1535.

**Comment by nickcernis** [comment]
This was fixed in 0.19.1 (out today). Thanks again for the report, @ericosullivanwp!
