### ISSUE TITLE
Repeatable group

### ISSUE THREAD

**Issue by warudin** [wpengine/atlas-content-modeler#582]
### Discussed in https://github.com/wpengine/atlas-content-modeler/discussions/581

<div type='discussions-op-text'>

<sup>Originally posted by **warudin** June 30, 2022</sup>
I've seen that ACM now has the ability to make fields repeatable. This is a real nice addition.

When comparing this feature to Advanced Custom Fields, I miss the ability to group multiple fields and make that whole group repeatable. There's probably several use cases in which being able to clone a complete set of fields is necessary.

Per instance: 
- I create a custom post-type listing 'Interesting Developers'.
- I want to list their accounts on different social media websites (Twitter, Facebook, GitHub, etc.) but I don't know up front which social media websites the user will want to insert
- Per social media-item I want to insert: their handle, actual name, URL, the logo from the social media website and their different fields of expertise.

It would be nice to be able to repeat these different fields as a group.</div>

**Comment by mindctrl** [comment]
Thank you for this feedback. I replied over in #581. I'll close this out so we can keep the discussion in one place.
