### ISSUE TITLE
Can't empty non-required field

### ISSUE THREAD

**Issue by rhmnaulia** [wpengine/atlas-content-modeler#587]
I can't empty ACM input even if it's not required, the content came back after I updated the post

### To reproduce
1. Go to custom post type
2. Delete one text field until it's empty
3. Update and publish the post
4. The deleted text came back

### Expected behavior
Possible to empty non-required field

### Screenshots
First condition
![image](https://user-images.githubusercontent.com/42644135/177245954-0ec932af-69b1-4b8c-bf56-3324e6d779c7.png)
Second condition (delete text)
![image](https://user-images.githubusercontent.com/42644135/177246300-100c3fe0-a192-4f5d-ba1b-600bc4669ee8.png)
Third Condition (after clicking update button, the text came back)
![image](https://user-images.githubusercontent.com/42644135/177246475-55c0341c-f6a9-46d1-8f6a-39fe4a2d8dfb.png)

### Version information
- Plugin version: 0.18.0 and 0.19.0
- WordPress version: 6.0
- Operating system: Windows/MacOS
- Browser: Chrome

**Comment by nickcernis** [comment]
This was fixed in 0.19.1 (out now). Thanks again for filing the issue, @rhmnaulia!
