### ISSUE TITLE
ACM Model Mixed Up

### ISSUE THREAD

**Issue by ttstauss** [wpengine/atlas-content-modeler#626]
We have a model for a repeating WYSIWYG (rich text field). Whenever we query the field we get errors such as the following:

```
  "errors": [
    {
      "debugMessage": "strpos(): Argument #1 ($haystack) must be of type string, array given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 39,
          "column": 5
        }
      ],
      "path": [
        "facultyMember",
        "publications"
      ]
    }
  ],
```

When I attempt to reproduce (by creating another model with the same set up) I get the opposite issue:
```
"errors": [
    {
      "debugMessage": "array_map(): Argument #2 ($array) must be of type array, string given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 39,
          "column": 5
        }
      ],
      "path": [
        "facultyMember",
        "publicationsWorks2"
      ]
    },
    {
      "debugMessage": "strpos(): Argument #1 ($haystack) must be of type string, array given",
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 40,
          "column": 5
        }
      ],
      "path": [
        "facultyMember",
        "publications"
      ]
    }
  ],
```

How can we modify the schema once created (we have a lot of posts using this field and would rather just fix the existing field than have to delete all the existing content and reenter)?

### To reproduce
1. Create a model (i.e. faculty) with a field like the one depicted in the screenshot below.
2. Create a new faculty member.
3. Query the new faculty member (should show no error).
4. Go back and add one or two WYSIWYG entries.
5. Query the faculty member again (there's an error).

### Expected behavior
The query should expect an array, not a string (since it's a repeater field).

### Screenshots
Here is the model in question:

![model](https://user-images.githubusercontent.com/15224340/197909027-6e34c4d0-3521-4d88-a098-54f4b2d6eda2.png)

| | Empty | Single Item | Multiple Items |
| --- | --- | --- | --- |
| Data | ![empty](https://user-images.githubusercontent.com/15224340/197909043-e00945da-ca74-498c-99db-a2ce8b2a0040.png) | ![one-item](https://user-images.githubusercontent.com/15224340/197909066-ba62ab8f-920a-4614-90f7-8bb9c21c18d3.png) | ![two-items](https://user-images.githubusercontent.com/15224340/197909087-746af548-da4a-46a7-8d3e-175e8a9b325b.png) |
| Query Result | ![Screenshot 2022-10-31 121259](https://user-images.githubusercontent.com/15224340/199080048-553a54dc-3baf-4198-942e-b11672cd8ab4.png) | ![one-item-query](https://user-images.githubusercontent.com/15224340/197909299-c2a2bab8-3b8d-4c84-bf26-d8816329f303.png) | ![two-items-query](https://user-images.githubusercontent.com/15224340/197909319-19fb74ed-9d60-49ba-af95-643eb874c686.png) |
| Database Entry | | ![one-item-database](https://user-images.githubusercontent.com/15224340/197909460-b0477e34-d70e-49c9-83a7-676a95846182.png) | ![two-items-database](https://user-images.githubusercontent.com/15224340/197909468-a81b01ba-15ad-4382-9843-247d35de0d2f.png) |

The same results presented above reverse when I attempt to recreate the model.

### Version information
- Plugin version: 0.22.0
- WordPress version: 6.0.3
- Operating system: Linux
- Browser: Chrome

### Additional context
We can't figure out how this scenario happened (did we change something that caused it to break).

**Comment by Androbas** [comment]
I have the same issue,
A workaround I found is to have all rich text repeatable fields with some text.
If a post of that type doesn't have any text in that field I get the same error

**Comment by ttstauss** [comment]
Any update on this?

**Comment by mindctrl** [comment]
@ttstauss @Androbas can you try this PR to see if it fixes the issue for you? https://github.com/wpengine/atlas-content-modeler/pull/655

**Comment by ttstauss** [comment]
@mindctrl, sorry for the delay in getting back to you. I'm ready to test this out, but I see that you already merged. I imagine it's already been tested. I'd still like to test it myself so I can go through the testing flow in the future. I have the project set up locally, but I'm trying to figure out how to get a build folder outputted so I can use that in my local WordPress dev environment. How do I go about doing that?

**Comment by mindctrl** [comment]
Hey @ttstauss, thanks for circling back and testing! When you check out the repo locally, you can run the following commands to get the plugin running:
- npm ci
- npm run build

Let me know if you have any issues with that. Happy to help.

**Comment by ttstauss** [comment]
@mindctrl, perfect. I got it set up and currently testing it. So far, I'm still seeing the "strpos(): Argument #1 ($haystack) must be of type string, array given" issue, but I may be doing something wrong. Still looking.

**Comment by ttstauss** [comment]
I think it has to do with the fact that the `isRepeatableRichText"` field is string `"false"` and not boolean `false` (we want it to be `true`).

```
      "1652727982953": {
        "show_in_rest": true,
        "show_in_graphql": true,
        "type": "richtext",
        "id": "1652727982953",
        "position": "100000",
        "name": "Publications & Works",
        "slug": "publications",
        "isRepeatableRichText": "false",
        "description": ""
      },
```

I have no idea why that's a string `"false"` instead of a boolean `false`.

I edited the value to a boolean `true` in the database, and it seems to have fixed the issue.

I also expanded the options to this, and it still seems to work fine:

```
      "1652727982953": {
        "show_in_rest": true,
        "show_in_graphql": true,
        "type": "richtext",
        "id": "1652727982953",
        "position": "100000",
        "name": "Publications & Works",
        "slug": "publications",
        "isRepeatableRichText": true,
        "description": "",
        "minChars": "",
        "maxChars": "",
        "minRepeatable": "",
        "maxRepeatable": "",
        "open": false,
        "editing": false
      },
```

Exporting the JSON helped lead me in the right direction!

**Comment by mindctrl** [comment]
@ttstauss thanks for the update! Glad you figured it out. I'll file an issue for this, as it seems like I've seen it once before somewhere.
