### ISSUE TITLE
Internal server error occurring with relationship fields

### ISSUE THREAD

**Issue by imjlk** [wpengine/atlas-content-modeler#643]
### To reproduce
1. Create New Models A & B
2. Edit A has a B as a relationship field (1:1 or any relationship)
3. Add New A Post with an empty B field.
4. See the below graphql query result 

```
{
  As {
    edges {
      node {
        id
        Bs {
          edges {
            node {
              id
            }
          }
        }
      }
    }
  }
}
```

### Expected behavior

I don't know well the graphql spec & wpgraphql plugin in detail, but it would not return an error if an empty array is returned. (or allow a null result)

If I'm using the wrong query, please let me know.

### Screenshots
I attached my test model export, and debug log on graphql ide

[download models](https://drive.google.com/open?id=11NFgPRlCv4F6h2n8ubB9AIKPJqpZH1lr)

[download log](https://drive.google.com/open?id=11RaAlRduZQbjiOM1QAMbBLU_7yeyS63C)

### Version information
- Plugin version:
  - ACM: 0.23.0
  - Wpgraphql: 1.13.7
- WordPress version: 6.1.1
- Browser: Chrome

### Additional context

https://github.com/wpengine/atlas-content-modeler/blob/44360ffe11538525a07d7025d33063f9fd36d24e/includes/content-registration/custom-post-types-registration.php#L745-L749

For my purposes (one-to-many relationship), I just modified the line above to:
```
	// return array();
	$relationship_ids = [1]; // hello world post id 😭
```

**Comment by Ifletcher668** [comment]
I'm seeing this behavior as well. The internal server error is coming from a `found null on non-nullable` field, which is defined in the schema as per WPGraphql's default behavior. The error happens *sometimes on Previews and all the time when I have a relationship field I have marked as _optional_ in the ACM gui

**Comment by mindctrl** [comment]
@imjlk @Ifletcher668 thank you for the report and your patience. We'll be working on this bug this week and should have a release ready shortly after.

**Comment by imjlk** [comment]
Now it works fine in wpgraphql, but I get an error in the Apollo client(with Faust.js) when the node is empty.

**Comment by mindctrl** [comment]
@imjlk can you provide more info to help us debug? What error are you getting? Which versions of ACM, Faust, and WPGraphQL are you running?

**Comment by imjlk** [comment]
Sorry, I check again and It works fine.

Version Info:
- @faustwp/core: 0.2.7
- @apollo/client: 3.6.6
- Wp-graphql: 1.14.0
- FaustWP: 0.8.4
- ACM: 0.24.0
