### ISSUE TITLE
Allow relationship field position to be editable from both parent models

### ISSUE THREAD

**Issue by TMUND** [wpengine/atlas-content-modeler#645]
Moving issue over from Discord channel. 

When two models have a relationship field (A to B) I should be able to edit the field position on both model A and model B. Currently I can only edit the position on model A. 

### To reproduce
1. Create two distinct models
2. Create a relationship field on model A to model B
3. Create content using model B
4. Verify relationship field shows up on the model but field position on the page is not editable

### Expected behavior

* Relationship Field position is editable from both linked models

### Screenshots

From Jeff Everheart on Discord: 

>I can replicate this, and it looks like the relationship field gets set to a default position value of 10000, so that it overrides whatever is after it
> This is where they are ordered: https://github.com/wpengine/atlas-content-modeler/blob/364f60e9f80831601d1cfaccd4f5d60f575ac71c/includes/publisher/lib/field-functions.php#L40
![Screen_Shot_2023-02-01_at_4 12 07_PM](https://user-images.githubusercontent.com/10443437/217360360-20c9ab45-0fd8-4ee5-8d0a-916e0c251d70.png)

**Comment by mindctrl** [comment]
Thanks for the request. Since ACM has entered an end-of-life phase and won't be receiving any new features like this, I'm going to close this issue. Source: https://github.com/wpengine/atlas-content-modeler/blob/main/docs/end-of-life/index.md
