### ISSUE TITLE
Relationship field is displaying all model entries after some time

### ISSUE THREAD

**Issue by NazarTikhoniuk** [wpengine/atlas-content-modeler#665]
When trying to add a new entry for a model with a relationship field, after a while list of all entries for the related model will appear in the field.
Tested it both for the custom theme and clean WordPress installation.

### To reproduce
1. Create a model, add any fields and add a few entries to it.
2. Create another model and add a relationship field connecting the first created model.
3. Go to the "Add New" screen of the second created model (with relationship field) and wait a while.
4. See the list of all entries of the first created model appear.

### Expected behavior
Only related entries of another model should be displayed.

### Screenshots
![image](https://github.com/wpengine/atlas-content-modeler/assets/23106114/14a4f229-416c-4632-a7d4-323f84ec68b5)

### Version information
- Plugin version: 0.24.0
- WordPress version: 6.2.2
- Operating system: MacOS Ventura 13.5 with running WordPress on Docker Desktop 4.19.0 and Docker Engine 23.0.5
- Browser: Chrome 115.0.5790.114 (arm64)

### Additional context
It is only a visual issue. After publishing or updating an entry, all entries from the list of the related model are not saved.

On "Add New":
![image](https://github.com/wpengine/atlas-content-modeler/assets/23106114/e16aac2a-62b5-45b6-9ea2-6d244dbe6928)

Right after publishing:
![image](https://github.com/wpengine/atlas-content-modeler/assets/23106114/3ccfa5ad-e960-43cd-8d9f-b780a4140410)

**Comment by mindctrl** [comment]
@NazarTikhoniuk thank you for the report. As you noted, it's a visual bug. We're tracking it here https://github.com/wpengine/atlas-content-modeler/issues/627. I'll close this one out and leave the original one open, and link back to here for additional context.
