### ISSUE TITLE
ACM: Empty repeater fields show a list of entries when browser tab loses and regains focus

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/atlas-content-modeler#678]
## To reproduce

- Create two models A and B related via a many-to-many relationship field.
- Create multiple B entries.
- Create a new A entry but do not relate it to any Bs yet.
- Open a new tab and then return to the original tab for the new A entry.

The “Bs” relationship field will refresh, showing all B entries even though you did not add any related B entries manually.

## Expected behavior

Relationship fields should not update on tab focus to show entries if none are set for that field.

## Resources

Has been reported several times. Write up here: https://github.com/wpengine/atlas-content-modeler/issues/627

**Comment by mindctrl** [comment]
Fixed in https://github.com/wpengine/atlas-content-modeler/pull/683
