### ISSUE TITLE
Fix e2e test workflow

### ISSUE THREAD

**Issue by mindctrl** [wpengine/atlas-content-modeler#682]
The Codeception e2e tests fail randomly in this repo. Sometimes it's a data import issue, others it's an error about tables not being locked.

Example failure for the table lock error: https://app.circleci.com/pipelines/github/wpengine/atlas-content-modeler/3814/workflows/c18909eb-b325-45b1-a16a-3ffb032e6308/jobs/43051

Example failure for the data import error (We've seen similar errors on the Faust.js repo): https://app.circleci.com/pipelines/github/wpengine/atlas-content-modeler/3811/workflows/4fe8877f-3a86-4665-a01a-b5f9b018965b/jobs/43015

### Expected behavior
Tests run more reliably and don't require re-runs all the time.

**Comment by matthewguywright** [comment]
Make sure to check these errors are still happening.
